
name: Docker Image CI

on: 
 push:
  branches:
    - master
jobs:
  build-Docker-Image: 
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - name: Obtaining the tag. . .
      uses: xom9ikk/version-by-tag@v1
      id: version_by_tag
    - name: Login to Docker Hub. . .
      uses: docker/login-action@v2.1.0
      with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build and push the Image. . .
      uses: docker/build-push-action@v3.2.0
      with:
        push: true
        tags: landerf/clara_oswlad:latest,landerf/clara_oswlad:${{steps.version_by_tag.outputs.tag}}
